blog/about/urls.py
from django_distill import distill_path
from . import views


app_name = "about"
urlpatterns = [
    distill_path("", views.AboutTemplateView.as_view(), name="index")
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django_distill import distill_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('blog/', include('blog_app.urls')),
    path('about/', include('about.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_app/urls.py
from django.utils import timezone
from django_distill import distill_path
from .models import Article
from . import views

def get_years():
    years = Article.objects.filter(active=True, pub_date__lte=timezone.now().date()).values_list('pub_date__year', flat=True).distinct()
    for year in years:
        yield {'year': year}

def get_articles():
    articles = Article.objects.filter(active=True, pub_date__lte=timezone.now().date()).values_list('pub_date__year', 'slug')
    print(articles)
    for year, slug in articles:
        yield {'year': year,'slug': slug}

app_name = "blog_app"
urlpatterns = [
    distill_path("", views.ArticleHelperView, name="blog"),
    distill_path("<int:year>/", views.ArticleYearArchiveView.as_view(), name="articles", distill_func=get_years),
    distill_path("<int:year>/<slug:slug>/", views.ArticleDetailView.as_view(), name="article", distill_func=get_articles),
]

blog/core/urls.py
from django_distill import distill_path
from . import views


app_name = "core"
urlpatterns = [
    distill_path("", views.HomeTemplateView.as_view(), name="home")
]

blog/about/models.py
from django.db import models


class Tech(models.Model):
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to="about/techs")
    def __str__(self):
        return self.name

class Certification(models.Model):
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to="about/certs")
    def __str__(self):
        return self.name

blog/blog_app/models.py
from django_ckeditor_5 import fields
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from random import randint, sample
from core.models import Portrait, SiteSettings


class Tag(models.Model):
    tag = models.CharField(max_length=20, unique=True)
    def __str__(self):
        return self.tag

class Article(models.Model):
    headline = models.CharField(max_length=200)
    description_tag = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    pub_date = models.DateField()
    thumbnail = models.ImageField(blank=True, upload_to="blog_app/article/thumbnails")
    featured = models.BooleanField(default=True)
    active = models.BooleanField(default=False)
    article = fields.CKEditor5Field()
    slug = models.SlugField(max_length=60, unique=True, blank=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.headline)
            while True:
                if not Article.objects.filter(slug=self.slug).exists():
                    break
                self.slug = f"{self.slug}{randint(0,9)}"
        if not self.description_tag:
            self.description_tag = self.headline
        super(Article, self).save(*args, **kwargs)
    def __str__(self):
        return self.headline
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            return SiteSettings.get().placeholder_thumbnail.url
    def get_related(self):
        current_article_tags = self.tags.all()
        related_articles = Article.objects.filter(tags__in=current_article_tags).exclude(id=self.id).exclude(active=False).distinct()
        return sample(list(related_articles), min(3, related_articles.count()))

blog/core/models.py
from django.db import models


class Portrait(models.Model):
    name = models.CharField(max_length=25, unique=True)
    email_address = models.EmailField()
    portrait_photo = models.ImageField(upload_to="core/portraits")
    def __str__(self):
        return f"Portrait photo of: {self.name}."

class SiteSettings(models.Model):
    class Meta:
        verbose_name = "Site Settings"
        verbose_name_plural = "Site Settings"
    id = models.PositiveSmallIntegerField(primary_key=True, default=1, editable=False)
    last_modified = models.DateTimeField(auto_now=True)
    sitename = models.CharField(max_length=30)
    home_photo = models.ImageField(upload_to="core/sitesettings/home_photo")
    home_text = models.TextField()
    placeholder_thumbnail = models.ImageField(upload_to="core/sitesettings/placeholder_thumbnail", verbose_name="Placeholder article thumbnail")
    comment_portrait = models.ImageField(upload_to="core/sitesettings/comment_portrait")
    about_photo = models.ImageField(upload_to="core/sitesettings/about_photo")
    about_text = models.TextField()
    favicon = models.ImageField(upload_to="core/sitesettings/favicon", blank=True) 
    home_description_tag = models.TextField()
    blog_description_tag = models.TextField()
    about_description_tag = models.TextField()
    email = models.EmailField()
    github_link = models.URLField(blank=True)
    discord_link = models.URLField(blank=True)
    def __str__(self):
        return "Site Settings"
    def get():
        return SiteSettings.objects.get(pk=1)

blog/about/views.py
from django.views.generic import TemplateView
from .models import Certification, Tech
from core.models import SiteSettings


class AboutTemplateView(TemplateView):
    template_name = "about/about.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sitesettings"] = SiteSettings.get()
        context["techs"] = Tech.objects.all()
        context["certs"] = Certification.objects.all()
        return context

blog/blog_app/views.py
from django.utils import timezone
from django.http import Http404
from django.views.generic import DetailView, YearArchiveView
from .models import Article
from core.models import SiteSettings


class ArticleYearArchiveView(YearArchiveView):
    queryset = Article.objects.filter(active=True)
    date_field = 'pub_date'
    make_object_list = True
    template_name = "blog_app/blog.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["sitesettings"] = SiteSettings.get()
        context['valid_years'] = Article.objects.filter(active=True, pub_date__lte=timezone.now().date()).values_list('pub_date__year', flat=True).distinct().order_by("-pub_date__year")
        context['current_year'] = self.get_year()
        return context

def ArticleHelperView(request):
    articles = Article.objects.filter(active=True, pub_date__lte=timezone.now().date())
    if articles.exists():
        last_year = articles.latest('pub_date').pub_date.year
        return ArticleYearArchiveView.as_view()(request, year=last_year)
    else:
        raise Http404

class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog_app/article.html"
    def get_queryset(self):
        return self.model.objects.filter(active=True, pub_date__lte=timezone.now().date())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sitesettings"] = SiteSettings.get()
        return context

blog/core/views.py
from django.views.generic import TemplateView
from django.utils import timezone
from blog_app.models import Article
from .models import SiteSettings


class HomeTemplateView(TemplateView):
    template_name = "core/home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sitesettings"] = SiteSettings.get()
        context["articles"] = Article.objects.filter(active=True, pub_date__lte=timezone.now().date(), featured=True).order_by("-pub_date")
        return context

blog/about/templates/about/about.html
{% extends "core/base.html" %}
{% load cdnstaticfiles %}

{% block title %}about | {{ sitesettings.sitename }}{% endblock %}
{% block about_focus %}class="focus"{% endblock %}
{% block description %}{{ sitesettings.about_description_tag }}{% endblock %}
{% block stylesheet %}<link rel="stylesheet" type="text/css" href="{% cdnstatic 'about/css/about.css' %}">{% endblock %}

{% block content %}
<article>
    <img src="{{ sitesettings.about_photo.url }}" alt="about photo">
    <p>{{ sitesettings.about_text }}</p>
</article>
<div id="techs">
    <h2>I have experience with:</h2>
    {% for tech in techs %}
    <img src="{{ tech.image.url }}" alt="{{ tech.name }}" title="{{ tech.name}}">
    {% endfor %}
</div>
<div id="certs">
    <h2>Certifications:</h2>
    {% for cert in certs %}
    <img src="{{ cert.image.url }}" alt="{{ cert.name }}" title="{{ cert.name}}">
    {% endfor %}
</div>
{% endblock %}

blog/blog_app/templates/blog_app/article.html
{% extends "core/base.html" %}
{% load cdnstaticfiles %}

{% block title %}{{ article.headline }} | {{ sitesettings.sitename }}{% endblock %}
{% block blog_focus %}class="focus"{% endblock %}
{% block description %}{{ article.description_tag }}{% endblock %}
{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% cdnstatic 'blog_app/css/article.css' %}">
<link rel="stylesheet" type="text/css" href="{% cdnstatic 'blog_app/css/vs2015.min.css' %}">
{% endblock %}

{% block content %}
<script src="{% cdnstatic 'blog_app/js/highlight.min.js' %}"></script>
<script>hljs.highlightAll();</script>
<h1 id="title">{{ article.headline }}</h1>
<article>{{ article.article | safe }}</article>
{% if article.get_related %}
<hr>
<h2 class="centerheading">Related articles.</h2>
<ul id="related">
    {% for related in article.get_related %}
    <li>
        <a href="{% url 'blog_app:article' related.pub_date.year related.slug %}">
            <img src="{{ related.get_thumbnail }}" alt="thumbnail">
        </a>
        <div class="text">
            <a href="{% url 'blog_app:article' related.pub_date.year related.slug %}">{{ related.headline }}</a>
            <p id="longdate">Published on {{ article.pub_date | date:"d-m-Y" }}.</p>
            <p id="shortdate">{{ article.pub_date | date:"d-m-Y" }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

blog/blog_app/templates/blog_app/blog.html
{% extends "core/base.html" %}
{% load cdnstaticfiles %}

{% block title %}blog {{ current_year }} | {{ sitesettings.sitename }}{% endblock %}
{% block blog_focus %}class="focus"{% endblock %}
{% block description %}{{ sitesettings.blog_description_tag }}{% endblock %}
{% block stylesheet %}<link rel="stylesheet" type="text/css" href="{% cdnstatic 'blog_app/css/blog.css' %}">{% endblock %}

{% block content %}
<div id="yearlist">
<h2>Year:</h2>
{% for year in valid_years %}
<a href="{% url 'blog_app:articles' year %}"{% if year == current_year %} class="focus"{% endif %}>{{ year }}</a>
{% endfor %}
</div>
<div id="articles">
    {% for article in article_list %}
    <div class="article">
        <a href="{% url 'blog_app:article' article.pub_date.year article.slug %}">
            <img src="{{ article.get_thumbnail }}" alt="thumbnail">
        </a>
        <article>
            <a href="{% url 'blog_app:article' article.pub_date.year article.slug %}">{{ article.headline }}</a>
            <p id="longdate">Published on {{ article.pub_date | date:"d-m-Y" }}.</p>
            <p id="shortdate">{{ article.pub_date | date:"d-m-Y" }}</p>
        </article>
    </div>
    {% empty %}
    <h2>There are no articles published in {{ current_year }}.</h2>
    {% endfor %}
</div>
{% endblock content %}

blog/core/templates/core/base.html
<!DOCTYPE html>
{% load cdnstaticfiles %}
<html lang="{% block lang %}en{% endblock %}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Arnout">
        <meta name="description" content="{% block description %}{% endblock %}">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% if sitesettings.favicon %}{{ sitesettings.favicon.url }}{% endif %}">
        <link rel="stylesheet" type="text/css" href="{% cdnstatic 'core/css/base.css' %}">
        {% block stylesheet %}{% endblock %}
    </head>
    <style>
        /* pt-sans-regular - latin */
        @font-face {
            font-display: swap;
            font-family: 'PT Sans';
            font-style: normal;
            font-weight: 400;
            src: url('{% cdnstatic "core/fonts/pt-sans-v17-latin-regular.woff2" %}') format('woff2');
        }
        /* freeman-regular - latin */
        @font-face {
            font-display: swap;
            font-family: 'Freeman';
            font-style: normal;
            font-weight: 400;
            src: url('{% cdnstatic "core/fonts/freeman-v1-latin-regular.woff2" %}') format('woff2');
        }
    </style>
    <body>
        <div id="wrapper">
            <nav>
                <div id="nav_container">
                    <a href="{% url 'core:home' %}" {% block home_focus %}{% endblock %}>home</a>
                    <a href="{% url 'blog_app:blog' %}" {% block blog_focus %}{% endblock %}>blog</a>
                    <a href="{% url 'about:index' %}" {% block about_focus %}{% endblock %}>about</a>
                </div>
            </nav>
            <main>
                {% block content %}
                {% endblock %}
            </main>
        </div>
        <footer>
            {% block footer %}
            <div>
                <a href="mailto:{{ sitesettings.email }}" title="email: {{ sitesettings.email }}">
                    <svg fill="#ffffff" viewBox="0 0 1920 1920" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1920 428.266v1189.54l-464.16-580.146-88.203 70.585 468.679 585.904H83.684l468.679-585.904-88.202-70.585L0 1617.805V428.265l959.944 832.441L1920 428.266ZM1919.932 226v52.627l-959.943 832.44L.045 278.628V226h1919.887Z" fill-rule="evenodd"/>
                    </svg>            
                </a>
                <a href="{{ sitesettings.github_link }}" title="github">
                    <svg viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="Dribbble-Light-Preview" transform="translate(-140.000000, -7559.000000)" fill="#ffffff">
                                <g id="icons" transform="translate(56.000000, 160.000000)">
                                    <path d="M94,7399 C99.523,7399 104,7403.59 104,7409.253 C104,7413.782 101.138,7417.624 97.167,7418.981 C96.66,7419.082 96.48,7418.762 96.48,7418.489 C96.48,7418.151 96.492,7417.047 96.492,7415.675 C96.492,7414.719 96.172,7414.095 95.813,7413.777 C98.04,7413.523 100.38,7412.656 100.38,7408.718 C100.38,7407.598 99.992,7406.684 99.35,7405.966 C99.454,7405.707 99.797,7404.664 99.252,7403.252 C99.252,7403.252 98.414,7402.977 96.505,7404.303 C95.706,7404.076 94.85,7403.962 94,7403.958 C93.15,7403.962 92.295,7404.076 91.497,7404.303 C89.586,7402.977 88.746,7403.252 88.746,7403.252 C88.203,7404.664 88.546,7405.707 88.649,7405.966 C88.01,7406.684 87.619,7407.598 87.619,7408.718 C87.619,7412.646 89.954,7413.526 92.175,7413.785 C91.889,7414.041 91.63,7414.493 91.54,7415.156 C90.97,7415.418 89.522,7415.871 88.63,7414.304 C88.63,7414.304 88.101,7413.319 87.097,7413.247 C87.097,7413.247 86.122,7413.234 87.029,7413.87 C87.029,7413.87 87.684,7414.185 88.139,7415.37 C88.139,7415.37 88.726,7417.2 91.508,7416.58 C91.513,7417.437 91.522,7418.245 91.522,7418.489 C91.522,7418.76 91.338,7419.077 90.839,7418.982 C86.865,7417.627 84,7413.783 84,7409.253 C84,7403.59 88.478,7399 94,7399"></path>
                                </g>
                            </g>
                        </g>
                    </svg>
                </a>
                <a href="{{ sitesettings.discord_link }}" title="discord">
                    <svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="512" cy="512" r="512" style="fill:#5865f2"/>
                        <path d="M689.43 349a422.21 422.21 0 0 0-104.22-32.32 1.58 1.58 0 0 0-1.68.79 294.11 294.11 0 0 0-13 26.66 389.78 389.78 0 0 0-117.05 0 269.75 269.75 0 0 0-13.18-26.66 1.64 1.64 0 0 0-1.68-.79A421 421 0 0 0 334.44 349a1.49 1.49 0 0 0-.69.59c-66.37 99.17-84.55 195.9-75.63 291.41a1.76 1.76 0 0 0 .67 1.2 424.58 424.58 0 0 0 127.85 64.63 1.66 1.66 0 0 0 1.8-.59 303.45 303.45 0 0 0 26.15-42.54 1.62 1.62 0 0 0-.89-2.25 279.6 279.6 0 0 1-39.94-19 1.64 1.64 0 0 1-.16-2.72c2.68-2 5.37-4.1 7.93-6.22a1.58 1.58 0 0 1 1.65-.22c83.79 38.26 174.51 38.26 257.31 0a1.58 1.58 0 0 1 1.68.2c2.56 2.11 5.25 4.23 8 6.24a1.64 1.64 0 0 1-.14 2.72 262.37 262.37 0 0 1-40 19 1.63 1.63 0 0 0-.87 2.28 340.72 340.72 0 0 0 26.13 42.52 1.62 1.62 0 0 0 1.8.61 423.17 423.17 0 0 0 128-64.63 1.64 1.64 0 0 0 .67-1.18c10.68-110.44-17.88-206.38-75.7-291.42a1.3 1.3 0 0 0-.63-.63zM427.09 582.85c-25.23 0-46-23.16-46-51.6s20.38-51.6 46-51.6c25.83 0 46.42 23.36 46 51.6.02 28.44-20.37 51.6-46 51.6zm170.13 0c-25.23 0-46-23.16-46-51.6s20.38-51.6 46-51.6c25.83 0 46.42 23.36 46 51.6.01 28.44-20.17 51.6-46 51.6z" style="fill:#fff"/>
                    </svg>
                </a>
            </div>
            {% endblock %}
        </footer>
    </body>
</html>

blog/core/templates/core/home.html
{% extends "core/base.html" %}
{% load cdnstaticfiles %}

{% block title %}home | {{ sitesettings.sitename }}{% endblock %}
{% block home_focus %}class="focus"{% endblock %}
{% block description %}{{ sitesettings.home_description_tag }}{% endblock %}
{% block stylesheet %}<link rel="stylesheet" type="text/css" href="{% cdnstatic 'core/css/home.css' %}">{% endblock %}

{% block content %}
<div id="articles">
{% for article in articles %}
<div class="article"{% if forloop.first %} id="bigarticle"{% endif %}>
    <a href="{% url 'blog_app:article' article.pub_date.year article.slug %}">
        <img src="{{ article.get_thumbnail }}" alt="thumbnail">
    </a>
    <article>
        <a href="{% url 'blog_app:article' article.pub_date.year article.slug %}">{{ article.headline }}</a>
        <p id="longdate">Published on {{ article.pub_date | date:"d-m-Y" }}.</p>
        <p id="shortdate">{{ article.pub_date | date:"d-m-Y" }}</p>
    </article>
</div>
{% endfor %}
</div>
<div id="sidebar">
    <img src="{{ sitesettings.home_photo.url }}" alt="portrait">
    <p>{{ sitesettings.home_text }}</p>
</div>
{% endblock %}